#ifndef VAR_UTILS_DEF
#define VAR_UTILS_DEF

#define NB_TEXTURE_BLOCK 7

#define SIZE_PIXELS 30
#define GAME_WIDTH 10
#define GAME_HEIGHT 20
#define POSITION_GAME 225

#define RESOLUTION_X 2*POSITION_GAME + GAME_WIDTH * SIZE_PIXELS
#define RESOLUTION_Y GAME_HEIGHT * SIZE_PIXELS

#define POSITION_INTERFACE_AVANT POSITION_GAME - (SIZE_PIXELS/1.5) * 4 - 20
#define POSITION_INTERFACE_APRES POSITION_GAME + GAME_WIDTH * SIZE_PIXELS + 20
#define POSITION_INTERFACE_Y 50

#define LONGUEUR_POWER 100

#define POSITION_LEVEL sf::Vector2f(POSITION_INTERFACE_APRES, SIZE_PIXELS * (GAME_HEIGHT - 4))
#define POSITION_LINE sf::Vector2f(POSITION_INTERFACE_APRES, SIZE_PIXELS * (GAME_HEIGHT - 6))
#define POSITION_SCORE sf::Vector2f(POSITION_INTERFACE_APRES, SIZE_PIXELS * (GAME_HEIGHT - 8))

#define POSITION_GAMEOVER sf::Vector2f((RESOLUTION_X) / 2 - 100, (RESOLUTION_Y) / 2 - 150)
#define POSITION_RESTART sf::Vector2f((RESOLUTION_X) / 2 - 125, (RESOLUTION_Y) / 2 + 50)
#define POSITION_ESCAPE_MENU sf::Vector2f((RESOLUTION_X) / 2 - 140, (RESOLUTION_Y) / 2 + 100)

#define POSITION_PAUSE sf::Vector2f((RESOLUTION_X) / 2 - 50, (RESOLUTION_Y) / 2 - 150)
#define POSITION_CONTINUER sf::Vector2f((RESOLUTION_X) / 2 - 175, (RESOLUTION_Y) / 2 + 50)


#define POSITION_TITRE_Y 25
#define POSITION_SOUS_TITRE_Y 100


#define SPEED_DEFAULT 50
#define UP_SPEED 15

#define LIMITE_FPS 100

#define TIME_COLLISION LIMITE_FPS / 2

#define POWER_LINE 5
#define POWER_MAX 100
#define POWER_USING 5
#define POWER_AUGMENT 0.5

#define SCORE_ONE_LINE 40
#define SCORE_TWO_LINE 100
#define SCORE_THREE_LINE 300
#define SCORE_FOUR_LINE 1200

#endif // !VAR_UTILS_DEF